In [6]:
import numpy as np 
numbers = np.array(range(1,11), copy=True)

print(numbers)


[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
ones = np.ones([1,4], dtype= np.float64)

print(ones)

zeros = np.zeros([1,4], np.float64)

print(zeros)

#this is not all ways 0 and can be zero 
empty = np.empty([1,4], dtype=np.float64)

print(empty)

[[1. 1. 1. 1.]]
[[0. 0. 0. 0.]]
[[0. 0. 0. 0.]]


In [23]:

matrix = np.eye(3,3,k=0)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
numbers2 = np.arange(1,5,0.25)

print(numbers2)

numnumbers2 = numbers2.astype(int)
print(numnumbers2)

[1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25 3.5  3.75 4.   4.25
 4.5  4.75]
[1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4]
